version: 2

jobs:
  "test":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-latest-node-with-gcloud:0.0.1
    steps:
      - checkout
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test
          no_output_timeout: 1m

  "publish_to_npm":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm login
      - run: npm run 2npm

workflows:
  version: 2
  test_and_publish:
    jobs:
      - "test"
      - "publish_to_npm":
          requires:
            - test
          filters:
            branches:
              only:
                - master